[package]
name = "rust-shexml-interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
rustemo = "0.7.0"
indoc = "2.0.5"

[dev-dependencies]
rustemo-compiler = "0.7.0"

[build-dependencies]
rustemo-compiler = "0.7.0"

